name: Run notebooks and report errors

on: [push, pull_request]

env:
  # Disable Tensorflow information messages
  TF_CPP_MIN_LOG_LEVEL: 1

jobs:
  run-notebooks:
    # Run only from the original repository
    if: github.repository == 'Qiskit/platypus'
    if: github.event.pull_request.user.login != 'gitlocalize-app[bot]'

    name: Run notebooks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # all_changed_files

      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Load pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: py-${{ hashFiles('converter/textbook-converter/requirements.txt') }}-${{ hashFiles('converter/textbook-converter/requirements-test.txt') }}

      - name: Install Python dependencies
        run: pip install -r converter/textbook-converter/requirements.txt -r converter/textbook-converter/requirements-test.txt

      - name: Get list of changed notebooks
        id: changed-notebooks
        uses: tj-actions/changed-files@v29.0.4
        with:
          files: notebooks/**.ipynb

      - name: Run notebooks
        run: python3 ./scripts/content_checks/nb_autorun.py ${{ steps.changed-notebooks.outputs.all_changed_files }} --fail-on-warning
